#Topics
drive_topic: "/audubon/drive" # Autonomous node publishes to mux
keyboard_topic: "/audubon/key" # Keyboard input
odom_topic: "/camera/odom/sample"    # odometry
get_servo_topic: "/sensors/servo_position_command"    # get servo position topic
set_servo_topic: "/commands/servo/position"    # set servo position topic
set_rpm_topic: "/commands/motor/speed"    # set rpm topic
estop_topic: "/audubon/estop"
control_mode_topic: "/audubon/motor/mode"
max_motor_RPM: "/audubon/motor/max_RPM"


# car 
car_gear_ratio: 23.6686390533 # changed from 23.66
car_wheel_radius: 0.052 # changed from 0.055
tire_circumference: 0.32656 # changed from 0.34558
max_servo_pos_in_radians: 0.7853981634 # pi/4 guess, needs to be measured
wheelbase: 0.34 # Measured manually on newer traxxas
steering_offset: 0.25
speed_to_erpm_gain: 0.1
speed_to_erpm_offset: 1
steering_angle_to_servo_gain: 1
steering_angle_to_servo_offset: 0

#PID gains for steering
kp_steer: 0.6
ki_steer: 0.001
kd_steer: 0.05

#PID gains for speed
kp_speed: 2.0
ki_speed: 0.07
kd_speed: 0.065

